version: "3.9"

services:
  db:
    image: postgres:15.1
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5433:5432
    env_file:
      - .env

  web:
    build: .
    command: /bin/bash -c "pip install -r requirements.txt; invoke runit"
    environment:
      PY_AUTORELOAD: true
    env_file:
      - .env
    volumes:
      - .:/src
      - ./static:/static
      - ./media:/media
    links:
      - db
    depends_on:
      - db
    expose:
      - 8000

  nginx:
    image: nginx
    links:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/static:ro
      - ./media:/media:ro
    ports:
      - 8000:80

volumes:
  pgdata:
