version: "3.9"

services:
  db:
    image: postgres:15.1
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env

  web:
    build: .
    command: /bin/bash -c "pip install -r requirements.txt; invoke runit"
    networks:
      - default
    env_file:
      - .env
    volumes:
      - .:/src
      - ./static:/static
      - ./media:/media
    links:
      - db
    depends_on:
      - db
    expose:
      - 8000

  nginx:
    image: nginx
    links:
      - web
    expose:
      - 80
    networks:
      - default
      - nginx-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/static:ro
      - ./media:/media:ro
    environment:
      - VIRTUAL_HOST=movie.phabious.store
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=movie.phabious.store
      - LETSENCRYPT_EMAIL=admin@movie.phabious.store

volumes:
  pgdata:

networks:
  nginx-proxy:
    external: true
  default: