version: 2.1

jobs:
  prospector:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run: pip install -r requirements-dev.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "~/.cache/pip"
            - /usr/local/lib/python3.10/site-packages
      - run: prospector apps

  test:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run: pip install -r requirements-dev.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "~/.cache/pip"
            - /usr/local/lib/python3.10/site-packages
      - run: coverage run ./manage.py test
      - run: coverage report --fail-under=85

workflows:
  check_code:
    jobs:
      - prospector
      - test
